"""Data quality checks and cleaning pipeline."""

from __future__ import annotations

from dataclasses import dataclass

import pandas as pd

from src.core.constants import PRICE_LIMIT_PCT, STANDARD_COLUMNS
from src.core.exceptions import DataQualityError


@dataclass
class QualityReport:
    """Data quality report generated by DataCleaner."""

    symbol: str
    total_rows: int
    negative_price_count: int
    zero_price_count: int
    extreme_change_count: int
    extreme_change_dates: list[str]
    zero_volume_count: int
    filled_count: int
    suspension_ranges: list[tuple[str, str]]

    def summary(self) -> str:
        parts = [
            f"symbol={self.symbol}",
            f"rows={self.total_rows}",
            f"negative_price={self.negative_price_count}",
            f"zero_price={self.zero_price_count}",
            f"extreme_change={self.extreme_change_count}",
            f"zero_volume={self.zero_volume_count}",
            f"filled={self.filled_count}",
            f"suspensions={len(self.suspension_ranges)}",
        ]
        return ", ".join(parts)


class DataCleaner:
    """L1/L2 quality checks and cleaning for OHLCV daily data."""

    def clean(self, df: pd.DataFrame, symbol: str) -> tuple[pd.DataFrame, QualityReport]:
        """
        Run L1 -> L2 cleaning and return (cleaned_df, quality_report).

        The input dataframe is never modified in-place.
        """
        self._validate_input_columns(df)
        working = df.copy(deep=True)
        working["date"] = pd.to_datetime(working["date"], errors="coerce")
        working = working.sort_values("date").reset_index(drop=True)

        l1_df, l1_stats = self._l1_detect_anomalies(working)
        l2_df, l2_stats = self._l2_fill_missing(l1_df)

        report = QualityReport(
            symbol=symbol,
            total_rows=int(len(df)),
            negative_price_count=int(l1_stats["negative_price_count"]),
            zero_price_count=int(l1_stats["zero_price_count"]),
            extreme_change_count=int(l1_stats["extreme_change_count"]),
            extreme_change_dates=list(l1_stats["extreme_change_dates"]),
            zero_volume_count=int(l1_stats["zero_volume_count"]),
            filled_count=int(l2_stats["filled_count"]),
            suspension_ranges=list(l2_stats["suspension_ranges"]),
        )
        return l2_df.reset_index(drop=True), report

    def _validate_input_columns(self, df: pd.DataFrame) -> None:
        required = set(STANDARD_COLUMNS)
        missing = sorted(required.difference(df.columns))
        if missing:
            raise DataQualityError(f"Missing required columns: {missing}")

    def _l1_detect_anomalies(self, df: pd.DataFrame) -> tuple[pd.DataFrame, dict]:
        """
        L1 checks:
        1. Drop rows with any negative or zero value in open/high/low/close.
        2. Flag daily close pct-change above +/-10% (strictly greater than 10%).
        3. Count volume==0 rows without removing them.
        """
        out = df.copy(deep=True)
        price_cols = ["open", "high", "low", "close"]
        out[price_cols] = out[price_cols].apply(pd.to_numeric, errors="coerce")
        out["volume"] = pd.to_numeric(out["volume"], errors="coerce")

        negative_mask = (out[price_cols] < 0).any(axis=1)
        zero_mask = (out[price_cols] == 0).any(axis=1)
        remove_mask = negative_mask | zero_mask

        filtered = out.loc[~remove_mask].copy()
        filtered = filtered.sort_values("date").reset_index(drop=True)

        close_pct = filtered["close"].pct_change()
        # Keep a tiny epsilon so exact 10% moves are not flagged by float noise.
        flagged_mask = close_pct.abs() > (PRICE_LIMIT_PCT + 1e-9)
        filtered["_flagged"] = flagged_mask.fillna(False)
        extreme_dates = (
            filtered.loc[filtered["_flagged"], "date"].dt.strftime("%Y-%m-%d").dropna().tolist()
        )

        stats = {
            "negative_price_count": int(negative_mask.sum()),
            "zero_price_count": int(zero_mask.sum()),
            "extreme_change_count": int(len(extreme_dates)),
            "extreme_change_dates": extreme_dates,
            "zero_volume_count": int((out["volume"] == 0).sum()),
        }
        return filtered, stats

    def _l2_fill_missing(self, df: pd.DataFrame) -> tuple[pd.DataFrame, dict]:
        """
        L2 checks:
        1. Forward-fill missing OHLC values.
        2. Detect suspension ranges where volume==0 for >=5 consecutive rows.
        """
        out = df.copy(deep=True)
        out = out.sort_values("date").reset_index(drop=True)

        fill_cols = ["open", "high", "low", "close"]
        before_missing = int(out[fill_cols].isna().sum().sum())
        out[fill_cols] = out[fill_cols].ffill()
        after_missing = int(out[fill_cols].isna().sum().sum())
        filled_count = before_missing - after_missing

        out["volume"] = pd.to_numeric(out["volume"], errors="coerce").fillna(0)
        zero_mask = out["volume"].eq(0)
        suspension_ranges: list[tuple[str, str]] = []

        start_idx: int | None = None
        for idx, is_zero in enumerate(zero_mask.tolist()):
            if is_zero and start_idx is None:
                start_idx = idx
            elif not is_zero and start_idx is not None:
                if idx - start_idx >= 5:
                    start_date = out.loc[start_idx, "date"].strftime("%Y-%m-%d")
                    end_date = out.loc[idx - 1, "date"].strftime("%Y-%m-%d")
                    suspension_ranges.append((start_date, end_date))
                start_idx = None

        if start_idx is not None and len(out) - start_idx >= 5:
            start_date = out.loc[start_idx, "date"].strftime("%Y-%m-%d")
            end_date = out.loc[len(out) - 1, "date"].strftime("%Y-%m-%d")
            suspension_ranges.append((start_date, end_date))

        stats = {
            "filled_count": int(filled_count),
            "suspension_ranges": suspension_ranges,
        }
        return out, stats


def compute_adjustment_factors(daily_df: pd.DataFrame, dividends_df: pd.DataFrame) -> pd.DataFrame:
    """
    Compute forward-adjustment factors for daily bars.

    factor on ex-date event:
        factor = 1 - (cash_dividend / ex_date_prev_close)
        factor *= 1 / (1 + stock_dividend / 10)  # when stock dividend exists

    Forward-adjusted rule:
    - latest side unchanged
    - historical prices are scaled down
    """
    if "date" not in daily_df.columns or "close" not in daily_df.columns:
        raise DataQualityError("daily_df must include date and close columns.")

    daily = daily_df.copy(deep=True)
    daily["date"] = pd.to_datetime(daily["date"], errors="coerce")
    daily = daily.dropna(subset=["date"]).sort_values("date").reset_index(drop=True)
    daily["adj_factor"] = 1.0
    if daily.empty:
        return daily

    if dividends_df is None or dividends_df.empty:
        return daily

    divs = dividends_df.copy(deep=True)
    if "date" not in divs.columns:
        return daily

    for col in ("cash_dividend", "stock_dividend"):
        if col not in divs.columns:
            divs[col] = 0.0

    divs["date"] = pd.to_datetime(divs["date"], errors="coerce")
    divs = divs.dropna(subset=["date"]).copy()
    if divs.empty:
        return daily

    divs["cash_dividend"] = pd.to_numeric(divs["cash_dividend"], errors="coerce").fillna(0.0)
    divs["stock_dividend"] = pd.to_numeric(divs["stock_dividend"], errors="coerce").fillna(0.0)
    divs["date_key"] = divs["date"].dt.strftime("%Y-%m-%d")
    grouped = divs.groupby("date_key", as_index=False)[["cash_dividend", "stock_dividend"]].sum()

    daily_close = pd.to_numeric(daily["close"], errors="coerce")
    daily["close"] = daily_close
    daily["date_key"] = daily["date"].dt.strftime("%Y-%m-%d")
    date_to_index = {key: idx for idx, key in enumerate(daily["date_key"].tolist())}

    event_factor_by_idx: dict[int, float] = {}
    for _, row in grouped.iterrows():
        date_key = str(row["date_key"])
        idx = date_to_index.get(date_key)
        if idx is None or idx <= 0:
            continue

        prev_close = daily.loc[idx - 1, "close"]
        if pd.isna(prev_close) or float(prev_close) <= 0:
            continue

        cash_dividend = float(row["cash_dividend"])
        stock_dividend = float(row["stock_dividend"])

        factor = 1.0 - (cash_dividend / float(prev_close))
        if stock_dividend > 0:
            factor *= 1.0 / (1.0 + (stock_dividend / 10.0))
        if factor <= 0:
            continue

        event_factor_by_idx[idx] = event_factor_by_idx.get(idx, 1.0) * factor

    cumulative = 1.0
    factors = [1.0] * len(daily)
    for idx in range(len(daily) - 1, -1, -1):
        factors[idx] = cumulative
        if idx in event_factor_by_idx:
            cumulative *= event_factor_by_idx[idx]

    daily["adj_factor"] = pd.Series(factors, dtype="float64")
    daily = daily.drop(columns=["date_key"])
    return daily


def adjust_prices(df: pd.DataFrame, dividends: pd.DataFrame, method: str = "forward") -> pd.DataFrame:
    """
    Apply dividend adjustment to OHLC prices.

    method:
    - forward: OHLC * adj_factor
    - raw: return unchanged copy
    """
    if method == "raw":
        return df.copy(deep=True)
    if method != "forward":
        raise ValueError("method must be 'forward' or 'raw'")

    adjusted = compute_adjustment_factors(df, dividends)
    out = adjusted.copy(deep=True)
    for col in ("open", "high", "low", "close"):
        if col in out.columns:
            out[col] = pd.to_numeric(out[col], errors="coerce") * out["adj_factor"]
    return out
